### ISSUE TITLE
Clone the repo failed as some file not upload it properly for git lfs 

### ISSUE THREAD

**Issue by 0xdadaking** [ParityAsia/hackathon-2022-winter#67]
Cloning into 'hackathon-2022-winter'...
remote: Enumerating objects: 4342, done.
remote: Counting objects: 100% (240/240), done.
remote: Compressing objects: 100% (205/205), done.
remote: Total 4342 (delta 36), reused 192 (delta 24), pack-reused 4102
Receiving objects: 100% (4342/4342), 278.07 MiB | 5.03 MiB/s, done.
Resolving deltas: 100% (1402/1402), done.
Downloading teams/32-zkNFT/src/sdk/data/pay/testnet/proving/mint.lfs (267 KB)
Error downloading object: teams/32-zkNFT/src/sdk/data/pay/testnet/proving/mint.lfs (682f7bd): Smudge error: Error downloading teams/32-zkNFT/src/sdk/data/pay/testnet/proving/mint.lfs (682f7bdc7de8a760b7415899d09ad1a6559cd81911597c0e3e14dfe3c536acd8): [682f7bdc7de8a760b7415899d09ad1a6559cd81911597c0e3e14dfe3c536acd8] Object does not exist on the server: [404] Object does not exist on the server

**Comment by juniuszhou** [comment]
please try remove lfs via `git lfs uninstall`

**Comment by 0xdadaking** [comment]
```
git lfs uninstall
```

> WARNING: error running /usr/lib/git-core/git 'config' '--includes' '--global' '--remove-section' 'filter.lfs': 'fatal: no such section: filter.lfs' 'exit status 128'
> open /home/billw/workspace/videown/tt/hackathon-2022-winter/.git/hooks/pre-push: no such file or directory
> Hooks for this repository have been removed.
> Global Git LFS configuration has been removed.

then I get a dirty workspace.

**Comment by 0xdadaking** [comment]
I fixed the clone problem use `GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/ParityAsia/hackathon-2022-winter.git`
